version: "3.7"

services:
  web:
    image: pkostelnik/open3a
    restart: unless-stopped
#    volumes:
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: PhaggyK26
      MYSQL_USER: open3a
      MYSQL_PASSWORD: open3a
      MYSQL_PORT: 3306
      MYSQL_DATABASE: open3a
      MYSQL_HOST: db
    networks:
      - open3a
    ports:
      - 80:8080
#      - 2019:2019
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: PhaggyK26
      MYSQL_USER: open3a
      MYSQL_PASSWORD: open3a
      MYSQL_PORT: 3306
      MYSQL_DATABASE: open3a
      MYSQL_HOST: db
    networks:
      - open3a
#    env_file:
    expose:
      - 3306

networks:
  open3a:
