version: "3.7"

services:
  app:
    image: php:7-fpm
#    volumes:
    expose:
      - 9000
    networks:
      - open3a
  web:
    image: pkostelnik/open3a:latest
#    volumes:
    networks:
      - open3a
    ports:
      - 80:80
  db:
    image: mariadb:latest
#    volumes:
    networks:
      - open3a
#    env_file:
    expose:
      - 3306

networks:
  open3a:
