version: "3.7"

services:
  app:
    image: php:7-fpm
    restart: unless-stopped
#    volumes:
    volumes_from:
      - web
    expose:
      - 9000
    networks:
      - open3a
  web:
    image: pkostelnik/open3a:latest
    restart: unless-stopped
#    volumes:
    networks:
      - open3a
    ports:
      - 80:80
      - 2019:2019
  db:
    image: mariadb:latest
    restart: unless-stopped
#    volumes:
    environment:
      MYSQL_ROOT_PASSWORD: PhaggyK26
      MYSQL_USER: open3a
      MYSQL_PASSWORD: open3a
      
    networks:
      - open3a
#    env_file:
    expose:
      - 3306

networks:
  open3a:
