CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE USER '$MYSQL_MAIL_USER'@'localhost' IDENTIFIED BY '$MYSQL_MAIL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON * . * TO '$MYSQL_ROOT_USER'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON * . * TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON * . * TO '$MYSQL_MAIL_USER'@'%' IDENTIFIED BY '$MYSQL_MAIL_ROOT_PASSWORD';
FLUSH PRIVILEGES;